### ISSUE TITLE
Error complemento Spanish Inspire Catastral Downloader

### ISSUE THREAD

**Issue by Juanjo1969** [north-road/slyr#156]
Hola
Complemento Spanish Inspire Catastral Downloader, falla al ejecutarse.
El problema es que me da fallos de ejecución de Python cuando solicito cualquier información catastral (parcelas, construcciones o direcciones), cumplimento los campos necesarios y al dar a descargar, me aparece el error que  pego a continuación al igual que los mensajes que aparecen en el registro de errores de Python. Cuando se produce el fallo, el cursor queda con el icono del círculo dando vueltas, para recuperar el icono normal he de reiniciar la aplicación. 
La versión que tengo de Qgis es la 3.28.6 Firenze.
Muchas gracias.

![image](https://github.com/north-road/slyr/assets/103095599/7f59b335-e130-4b39-9317-36a341f538cf)

2024-01-23T08:00:45     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 1346, in do_open
              h.request(req.get_method(), req.selector, req.data, headers,
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\http\client.py", line 1253, in request
              self._send_request(method, url, body, headers, encode_chunked)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\http\client.py", line 1299, in _send_request
              self.endheaders(body, encode_chunked=encode_chunked)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\http\client.py", line 1248, in endheaders
              self._send_output(message_body, encode_chunked=encode_chunked)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\http\client.py", line 1008, in _send_output
              self.send(msg)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\http\client.py", line 948, in send
              self.connect()
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\http\client.py", line 919, in connect
              self.sock = self._create_connection(
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\socket.py", line 843, in create_connection
              raise err
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\socket.py", line 831, in create_connection
              sock.connect(sa)
             socket.timeout: timed out
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Spanish_Inspire_Catastral_Downloader\Spanish_Inspire_Catastral_Downloader.py", line 337, in generate_download_url
              self.create_download_file(inecode_catastro, tipo, url_cadastre, wd)
              File "C:\Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Spanish_Inspire_Catastral_Downloader\Spanish_Inspire_Catastral_Downloader.py", line 362, in create_download_file
              request.urlretrieve(e_url, zip_file, self.reporthook)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 239, in urlretrieve
              with contextlib.closing(urlopen(url, data)) as fp:
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 214, in urlopen
              return opener.open(url, data, timeout)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 517, in open
              response = self._open(req, data)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 534, in _open
              result = self._call_chain(self.handle_open, protocol, protocol +
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
              result = func(*args)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 1375, in http_open
              return self.do_open(http.client.HTTPConnection, req)
              File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\urllib\request.py", line 1349, in do_open
              raise URLError(err)
             urllib.error.URLError:

**Comment by nyalldawson** [comment]
@Juanjo1969 this is the slyr repository, not the Spanish Inspire Catastral Downloader repository
