### ISSUE TITLE
USGS geological style "FGDC.stylx" conversion

### ISSUE THREAD

**Issue by alexCCI** [north-road/slyr#219]
**Describe the bug**
When converting Marker Symbols from the USGS geological style "FGDC.stylx," execution stops due to the following error:
AttributeError: 'QgsGeometryGeneratorSymbolLayer' object has no attribute 'size'.

**To Reproduce**
To reproduce the issue, select the algorithm "Convert STYLX to QGIS style XML", use the file FGDC.stylx available for download via the following link: https://ngmdb.usgs.gov/Info/standards/NCGMP09/docs/FGDC_STYLX.zip , and choose Marker Symbols as the type.

**Desktop (please complete the following information):**
OS : Windows 10
Version de QGIS : 3.34.13-Prizren
Version de Qt : 5.15.13
Version de Python : 3.12.7
Version de GDAL : 3.9.3
Version de GEOS : 3.13.0-CAPI-1.19.0
Version de Proj : Rel. 9.5.0, September 15th, 2024
Version de PDAL : 2.8.1 (git-version: a06325)
Version de SLYR : 7.4.1

**Additional context**
639/1891: 26.07.09
Traceback (most recent call last):
File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr\qgis_plugin\algorithms\stylx_to_xml.py", line 346, in processAlgorithm
qgis_symbol = SymbolConverter.Symbol_to_QgsSymbol(symbol, context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr\converters\symbols.py", line 414, in Symbol_to_QgsSymbol
SymbolConverter.add_symbol_layers(out, symbol, context)
File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr\converters\symbols.py", line 565, in add_symbol_layers
SymbolConverter.append_SymbolLayer_to_QgsSymbolLayer(out, layer, context)
File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr\converters\symbols.py", line 609, in append_SymbolLayer_to_QgsSymbolLayer
SymbolConverter.append_MarkerSymbolLayer(symbol, layer, context)
File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr\converters\symbols.py", line 685, in append_MarkerSymbolLayer
SymbolConverter.append_CIMVectorMarkerSymbolLayer(symbol, layer, context)
File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr\converters\symbols.py", line 2963, in append_CIMVectorMarkerSymbolLayer
target_size = sub_symbol_layer.size() * percent_size
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QgsGeometryGeneratorSymbolLayer' object has no attribute 'size'

Execution failed after 4.06 secondes

**Comment by nyalldawson** [comment]
@alexCCI are you a licensed version holder? If so, please email info@north-road.com for support
